version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 portal/manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
  postfix:
    image: juanluisbaptiste/postfix:latest
    expose:
      - "25"
    environment:
      SMTP_SERVER: smtp.mycompany.com
      SMTP_USERNAME: user@mycompany.com
      SMTP_PASSWORD: changeme
      SERVER_HOSTNAME: helpdesk.mycompany.com
